

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "DirectXPage.xaml.h"




void ::DXGameProgramming::DirectXPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///DirectXPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///DirectXPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the SwapChainBackgroundPanel named 'SwapChainPanel'
    SwapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SwapChainPanel"));
}

void ::DXGameProgramming::DirectXPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerMoved +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnPointerMoved);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerReleased +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnPointerReleased);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerPressed +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnDownButtonDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnDownButtonPointerEntered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerReleased +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnDownButtonUp);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnDownButtonUp);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerPressed +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnRightButtonDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnRightButtonPointerEntered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerReleased +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnRightButtonUp);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnRightButtonUp);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerPressed +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnUpButtonDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnUpButtonPointerEntered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerReleased +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnUpButtonUp);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnUpButtonUp);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerPressed +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnLeftButtonDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnLeftButtonPointerEntered);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerReleased +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnLeftButtonUp);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerExited +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::DXGameProgramming::DirectXPage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::OnLeftButtonUp);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

